export function buildMarketplace(plugins, meta = {}) {
  const { name = 'equipt', owner = 'equipt' } = meta;
  return {
    name,
    owner: { name: owner },
    plugins: [...plugins]
      .sort((a, b) => a.name.localeCompare(b.name))
      .map(p => ({ name: p.name, source: `./plugins/${p.name}`, description: p.description })),
  };
}

export function buildPluginManifest(plugin) {
  return {
    name: plugin.name,
    description: plugin.description,
    version: plugin.version ?? '0.1.0',
  };
}

function groupBy(items, keyFn) {
  const map = new Map();
  for (const item of items) {
    const k = keyFn(item);
    if (!map.has(k)) map.set(k, []);
    map.get(k).push(item);
  }
  return map;
}

const byName = (a, b) => a.name.localeCompare(b.name);

export function buildDirectory(assets) {
  const byPlugin = groupBy(assets, a => a.plugin);
  let md = '# Equipt Directory\n\n';
  md += '> Generated by `scripts/build.mjs` — do not edit by hand.\n\n';
  for (const plugin of [...byPlugin.keys()].sort()) {
    const items = byPlugin.get(plugin);
    md += `## ${plugin}\n\n`;
    const skills = items.filter(i => i.kind === 'skill').sort(byName);
    const agents = items.filter(i => i.kind === 'agent').sort(byName);
    if (skills.length) {
      md += `### Skills (${skills.length})\n\n`;
      for (const s of skills) md += `- **${s.name}** — ${s.description}\n`;
      md += '\n';
    }
    if (agents.length) {
      md += `### Agents (${agents.length})\n\n`;
      for (const a of agents) md += `- **${a.name}** — ${a.description}\n`;
      md += '\n';
    }
  }
  return md;
}
